# Generated by Django 4.2 on 2023-05-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
